### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by q2dg** [bromagosa/snap-interpreter#3]
Last commit is from 2 years ago...
Thanks

**Comment by bromagosa** [comment]
It is not currently maintained. It should work in 95% of the cases, the other 5% being those projects using blocks that didn't exist 2 years ago (not that many were added).

If I have the time soon, I may check for changes in the blocks library and update the project accordingly... there were also some core modifications that made Snap! much faster, I guess I should  look into those as well.

However, we may rebuild the command line Snap! interpreter some time soon. A student of ours has built a system that allows you to "hollow out" pieces in Snap! automatically. So, building the interpreter would just be a matter of telling this system to leave out all graphic stuff, then apply some other simple changes.

**Comment by q2dg** [comment]
Oooh, these expected changes are very promising!
Thanks
